edges = {
    'Alertness': ['Novice'],
    'Ambidextrous': ['Novice'],
    'Arcane Background': ['Novice'],
    'Arcane Resistance': ['Novice'],
    'Improved Arcane Resistance': ['Novice'],
    'Aristocrat': ['Novice'],
    'Attractive': ['Novice'],
    'Very Attractive': ['Novice'],
    'Berserk': ['Novice'],
    'Brave': ['Novice'],
    'Brawny': ['Novice'],
    'Brute': ['Novice'],
    'Charismatic': ['Novice'],
    'Elan': ['Novice'],
    'Fame': ['Novice'],
    'Famous': ['Seasoned'],
    'Fast Healer': ['Novice'],
    'Fleet-Footed': ['Novice'],
    'Linguist': ['Novice'],
    'Luck': ['Novice'],
    'Great Luck': ['Novice'],
    'Quick': ['Novice'],
    'Rich': ['Novice'],
    'Filthy Rich': ['Novice'],
    'Block': ['Novice'],
    'Improved Block': ['Veteran'],
    'Brawler': ['Seasoned'],
    'Bruiser': ['Seasoned'],
    'Calculating': ['Novice'],
    'Combat Reflexes': ['Seasoned'],
    'Counterattack': ['Seasoned'],
    'Improved Counterattack': ['Veteran'],
    'Dead Shot': ['Novice'],
    'Dodge': ['Seasoned'],
    'Improved Dodge': ['Veteran'],
    'Double Tap': ['Seasoned'],
    'Extraction': ['Novice'],
    'Improved Extraction': ['Seasoned'],
    'Feint': ['Novice'],
    'First Strike': ['Novice'],
    'Improved First Strike': ['Heroic'],
    'Free Runner': ['Novice'],
    'Frenzy': ['Seasoned'],
    'Improved Frenzy': ['Veteran'],
    'Giant Killer': ['Veteran'],
    'Hard to Kill': ['Novice'],
    'Harder to Kill': ['Veteran'],
    'Improvisational Fighter': ['Seasoned'],
    'Iron Jaw': ['Novice'],
    'Killer Instinct': ['Seasoned'],
    'Level Headed': ['Seasoned'],
    'Improved Level Headed': ['Seasoned'],
    'Marksman': ['Seasoned'],
    'Martial Artist': ['Novice'],
    'Martial Warrior': ['Seasoned'],
    'Mighty Blow': ['Novice'],
    'Nerves of Steel': ['Novice'],
    'Improved Nerves of Steel': ['Novice'],
    'No Mercy': ['Seasoned'],
    'Rapid Fire': ['Seasoned'],
    'Improved Rapid Fire': ['Veteran'],
    'Rock and Roll!': ['Seasoned'],
    'Steady Hands': ['Novice'],
    'Sweep': ['Novice'],
    'Improved Sweep': ['Veteran'],
    'Trademark Weapon': ['Novice'],
    'Improved Trademark Weapon': ['Seasoned'],
    'Two-Fisted': ['Novice'],
    'Two-Gun Kid': ['Novice'],
    'Command': ['Novice'],
    'Command Presence': ['Seasoned'],
    'Fervor': ['Veteran'],
    'Hold the Line': ['Seasoned'],
    'Inspire': ['Seasoned'],
    'Natural Leader': ['Veteran'],
    'Tactician': ['Seasoned'],
    'Master Tactician': ['Veteran'],
    'Artificer': ['Seasoned'],
    'Channeling': ['Seasoned'],
    'Concentration': ['Seasoned'],
    'Extra Effort': ['Seasoned'],
    'Gadgeteer': ['Seasoned'],
    'Holy/Unholy Warrior': ['Seasoned'],
    'Mentalist': ['Seasoned'],
    'New Powers': ['Novice'],
    'Power Points': ['Novice'],
    'Power Surge': ['Novice'],
    'Rapid Recharge': ['Seasoned'],
    'Improved Rapid Recharge': ['Veteran'],
    'Soul Drain': ['Seasoned'],
    'Wizard': ['Seasoned'],
    'Ace': ['Novice'],
    'Acrobat': ['Novice'],
    'Assassin': ['Novice'],
    'Investigator': ['Novice'],
    'Jack-Of-All-Trades': ['Novice'],
    'McGyver': ['Novice'],
    'Mr. Fix It': ['Novice'],
    'Scholar': ['Novice'],
    'Soldier': ['Novice'],
    'Thief': ['Novice'],
    'Woodsman': ['Novice'],
    'Bolster': ['Novice'],
    'Common Bond': ['Novice'],
    'Connections': ['Novice'],
    'Humiliate': ['Novice'],
    'Menacing': ['Novice'],
    'Provoke': ['Novice'],
    'Rabble-Rouser': ['Seasoned'],
    'Reliable': ['Novice'],
    'Retort': ['Novice'],
    'Streetwise': ['Novice'],
    'Strong Willed': ['Novice'],
    'Iron Will': ['Novice'],
    'Work the room': ['Novice'],
    'Work the Crowd': ['Seasoned'],
    'Beast Bond': ['Novice'],
    'Champion': ['Novice'],
    'Chi': ['Veteran'],
    'Danger Sense': ['Novice'],
    'Healer': ['Novice'],
    'Liquid Courage': ['Novice'],
    'Scavenger': ['Novice'],
    'Followers': ['Legendary'],
    'Professional': ['Legendary'],
    'Expert': ['Legendary'],
    'Master': ['Legendary'],
    'Sidekick': ['Legendary'],
    'Tough As Nails': ['Legendary'],
    'Weapon Master': ['Legendary'],
    'Master of Arms': ['Legendary']
}